### ISSUE TITLE
[BUG] Hud no longer visible, disapeared or is hidden

### ISSUE THREAD

**Issue by dafzor** [Larkinabout/fvtt-token-action-hud-core#109]
**Describe the bug**
The HUD is no longer visible in my normal campaign. Starting a new campain with just the HUD mod will work however.

When using the H shortcut key i get the following error:

````
token-action-hud-core.min.js:1  Uncaught TypeError: undefined. Cannot read properties of undefined (reading 'toggleHud')
[Detected 1 package: token-action-hud-core]
    at Object.onDown (token-action-hud-core.min.js:1:30981)
    at KeyboardManager._executeKeybind (foundry.js:2150:66)
    at KeyboardManager._processKeyboardContext (foundry.js:2191:33)
    at KeyboardManager._handleKeyboardEvent (foundry.js:2249:10)
    at foundry.js:1873:54
````

**Steps to reproduce**
1. Open regular campaign
2. Press H

**Versions:**
- Token Action HUD Core: 1.3.2
- Token Action HUD System:  token-action-hud-dnd5e 1.3.0/1.3.1 (update didn't fix)
- System: dnd5e 2.1.5
- Foundry VTT: 10.291
- Browser: Microsoft Edge 112.0.1722.48 (Official build) (64-bit) / Firefox 112.0.1 (64Bit)

**Additional context**
It was previously working, unloading all mods except HUD does not resolve the issue.

**Comment by Larkinabout** [comment]
Hi @dafzor, can you please try running the following in a macro script?: `game.settings.set('token-action-hud-core', 'enable', true)`

**Comment by Larkinabout** [comment]
Sorry, meant 'visible' not 'enable'.

**Comment by dafzor** [comment]
Running it as a macro of the type script had no apparent effect.

Running it in the development console outputted this:

```javascript
game.settings.set('token-action-hud-core', 'enable', true)
Promise { <state>: "fulfilled", <value>: true }
```

Tried it with a player and GM user.

Any file i can provide that would make it easier to debug? maybe the world folder?

**Comment by Larkinabout** [comment]
Sorry I messed up the instruction originally. Replace 'enable' with 'visible'.

**Comment by dafzor** [comment]
My apologies for not noticing, that said same result.

```javascript
game.settings.set('token-action-hud-core', 'visible', true)
Promise {<fulfilled>: true}
```

**Comment by Larkinabout** [comment]
That should have made the HUD visible if it was previously set to invisible by the hotkey. If that didn't work there must be other errors. Can you enable debugging for the module via the module setting and post the output when you click on a token.

**Comment by Larkinabout** [comment]
Also, have you disabled the 'Toggle HUD' hotkey?

**Comment by Larkinabout** [comment]
Hi @dafzor, in the latest release I have relocated the toggle to toggle the 'Enable HUD' module setting instead of a hidden setting. Can you see if this release resolves your issue?

**Comment by dafzor** [comment]
Since i can't reproduce the issue any more, I'll close. thanks for your time and patience.
