### ISSUE TITLE
[BUG] Socketlib Error When No GM Connected

### ISSUE THREAD

**Issue by Larkinabout** [Larkinabout/fvtt-token-action-hud-core#169]
**Describe the bug**
https://discord.com/channels/170995199584108546/722566083499786352/1130537177026150460
```
socketlib.js:335 Uncaught (in promise) SocketlibNoGMConnectedError: undefined. Could not execute handler 'getData' as GM, because all GMs disconnected while the execution was being dispatched.
[Detected 2 packages: socketlib, lib-wrapper]
    at socketlib.js:335:22
    at Array.filter (<anonymous>)
    at a.handleUserActivity (socketlib.js:330:72)
```

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Core 1.4.17.
