### ISSUE TITLE
[BUG] Clicking Item in Inventory Section fails while MidiQoL is enabled

### ISSUE THREAD

**Issue by ZBell** [Larkinabout/fvtt-token-action-hud-core#215]
**Describe the bug**
When clicking on a weapon in the Inventory section, while MidiQoL and its dependencies are enabled, the following error is generated in the console,
ils.js:2581 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'toLocaleLowerCase')
[Detected 4 packages: midi-qol, lib-wrapper, token-action-hud-dnd5e, token-action-hud-core]
    at hasCondition (utils.js:2581:20)
    at checkIncapacitated (utils.js:1740:6)
    at Item5e.doItemUse (itemhandling.js:225:88)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁CONFIG.Item.documentClass.prototype.use#0 (libWrapper-wrapper.js:189:20)
    at #W (token-action-hud-dnd5e.min.js:1:41224)
    at #Q (token-action-hud-dnd5e.min.js:1:39432)
    at RollHandler.handleActionClick (token-action-hud-dnd5e.min.js:1:38895)
    at RollHandler.handleActionClickCore (roll-handler.js:53:22)
    at actionClick (token-action-hud.js:336:34)
    at HTMLDivElement.<anonymous> (token-action-hud.js:471:13)
    at HTMLDivElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)

**Steps to reproduce**
1. Select a token
2. Mouseover/click the Inventory tab in the HUD
3. Click a Weapon

**Versions:**
- Token Action HUD Core: 1.5.2
- Token Action HUD System: token-action-hud-dnd5e 1.5.1
- System: dnd5e 2.4.0
- Foundry VTT: 11 Stable Build 315
- Browser: Foundry App

**Additional context**
MidiQoL - 11.2.3
DAE - 11.1.4
LibWrapper - 1.12.13.0
SocketLib - 1.0.13

**Comment by ZBell** [comment]
I know this might be a MidiQoL bug, but I thought I would let you know, in case it was something on this end.  Thanks!

**Comment by ZBell** [comment]
Definitely MidiQoL specific, for anyone else who sees this I was given the following successful workaround,
"For now disable the option Incapacitated actors cannot take actions or reactions in MidiQOL settings > Workflow settings > Mechanics tab and should be OK"
