### ISSUE TITLE
[BUG] HUD does not appear for only one player (PF2E)

### ISSUE THREAD

**Issue by dzsilberstein** [Larkinabout/fvtt-token-action-hud-core#282]
**Describe the bug**
The overall HUD is not appearing for one player but shows up fine for the Gamemaster and the other 3 players in the same game.

**Versions:**
- Token Action HUD Core: 2.0.5
- Token Action HUD System: PF2E 2.0.0
- System: Pathfinder 2E
- Foundry VTT: 12.331

**Comment by Larkinabout** [comment]
Afraid I will need more info. Can you log in as the player and see if you get the same issue. If so, press F12 and see if there are any red errors in the console.

**Comment by dzsilberstein** [comment]
There was this error when I had Dorako UI enabled. I disabled Dorako UI but the HUD still did not show up.

Error: Error thrown in hooked function '' for hook 'renderTokenActionHud'. Cannot read properties of undefined (reading 'dataset')
[Detected 1 package: pf2e-dorako-ui(3.7.5)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
    at #call (foundry.js:636:36)
    at Hooks.callAll (foundry.js:589:17)
    at #doEvent (foundry-esm.js:44921:17)
    at #render (foundry-esm.js:44366:20)
    at async Semaphore._try (foundry-esm.js:6645:19)Caused by: TypeError: Cannot read properties of undefined (reading 'dataset')
[Detected 1 package: pf2e-dorako-ui(3.7.5)]
    at Object.fn (ui-theme.js:84:20)
    at #call (foundry.js:632:20)
    at Hooks.callAll (foundry.js:589:17)
    at #doEvent (foundry-esm.js:44921:17)
    at #render (foundry-esm.js:44366:20)
    at async Semaphore._try (foundry-esm.js:6645:19)
onError @ foundry.js:655Understand this errorAI
foundry.js:635 Foundry VTT | Error thrown in hooked function '' for hook 'renderTokenActionHud'
#call @ foundry.js:635Understand this warningAI
foundry.js:655 Error: Error thrown in hooked function '' for hook 'renderTokenActionHud'. Cannot read properties of undefined (reading 'dataset')
[Detected 1 package: pf2e-dorako-ui(3.7.5)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
    at #call (foundry.js:636:36)
    at Hooks.callAll (foundry.js:589:17)
    at #doEvent (foundry-esm.js:44921:17)
    at #render (foundry-esm.js:44366:20)
    at async Semaphore._try (foundry-esm.js:6645:19)Caused by: TypeError: Cannot read properties of undefined (reading 'dataset')
[Detected 1 package: pf2e-dorako-ui(3.7.5)]
    at Object.fn (ui-theme.js:84:20)
    at #call (foundry.js:632:20)
    at Hooks.callAll (foundry.js:589:17)
    at #doEvent (foundry-esm.js:44921:17)
    at #render (foundry-esm.js:44366:20)
    at async Semaphore._try (foundry-esm.js:6645:19)
onError @ foundry.js:655Understand this errorAI
game:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was receivedUnderstand this errorAI

**Comment by ArchaeanDragon** [comment]
Also having this problem, as the player having it. Here's what I see in the main browser console log that seems relevant:

Uncaught (in promise) TypeError: U[n] is undefined
[Detected 1 package: token-action-hud-core(2.0.7)]
    switchCSS http://(redacted):30000/modules/token-action-hud-core/dist/token-action-hud-core.min.mjs:1
    registerCoreModule http://(redacted):30000/modules/token-action-hud-core/dist/token-action-hud-core.min.mjs:1
token-action-hud-core.min.mjs:1:12637

There's another version of the same error in the F12 screen:
Uncaught (in promise) TypeError: U[n] is undefined
[Detected 1 package: token-action-hud-core(2.0.7)]
    switchCSS utils.mjs:514
    registerCoreModule main.mjs:39

**Comment by tucos9** [comment]
I am also getting the exact same error
```
Uncaught (in promise) TypeError: Cannot destructure property 'file' of 'U[n]' as it is undefined.
    at Utils.switchCSS (utils.mjs:514:13)
    at Object.registerCoreModule [as fn] (main.mjs:39:9)
switchCSS @ utils.mjs:514
registerCoreModule @ main.mjs:39
await in registerCoreModule
#call @ foundry.js:632
call @ foundry.js:614
(anonymous) @ token-action-hud-pf2e.min.js:1
#call @ foundry.js:632
callAll @ foundry.js:589
registerApi @ api.mjs:29
#call @ foundry.js:632
callAll @ foundry.js:589
setupGame @ foundry.js:9098
```

Using Microsoft Edge Version 131.0.2903.99 (Official build) (64-bit)
