### ISSUE TITLE
[BUG] HUD fails to appear due to undefined tooltipData

### ISSUE THREAD

**Issue by jbrecht** [Larkinabout/fvtt-token-action-hud-core#298]
**Describe the bug**
The menus do not appear in one of my two games any more. The first time you click on a token, the following error appears in the console:
```
action-handler.js:1242 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')
[Detected 2 packages: token-action-hud-dnd5e(2.0.2), token-action-hud-core(2.0.10)]
    at #k (action-handler.js:1242:51)
    at action-handler.js:299:31
```

the code throwing the error is this:

```
    async #getTooltip(tooltipData) {
      if (this.tooltipsSetting === "none") return "";
      if (typeof tooltipData === "string") return tooltipData;

      const name = game.i18n.localize(tooltipData.name);
```
Specifically, it's **tooltipData.name**, tooltipData is undefined.

**Steps to reproduce**
1. Launch Foundry 
2. Click on a token
3. Observe no menus appear and the error mentioned above appears in the console.

**Versions:**
- Token Action HUD Core: [2.0.10]
- Token Action HUD System: [token-action-hud-dnd5e 2.0.2]
- System: [dnd5e 4.1.2]
- Foundry VTT: [12.331]
- Browser: [Google Chrome 131.0.6778.109, Safari (not sure the version, just reported by a player.]

**Additional context**
This same configuration of versions is working for me in another Game World I have. Works consistently in one world while failing consistently in another.

**Comment by jbrecht** [comment]
Followup - after setting the breakpoint and seeing the value of the tooltipData in the calls leading up to the problem were conditions, I checked on something. The world that was failing had the Combat Utility Belt module's "Enhanced Conditions" running. These conditions must be what breaks the HUD. the getTooltip function should probably just check for tooltipData being undefined and return "" in that case.

**Comment by MD25287** [comment]
> Followup - after setting the breakpoint and seeing the value of the tooltipData in the calls leading up to the problem were conditions, I checked on something. The world that was failing had the Combat Utility Belt module's "Enhanced Conditions" running. These conditions must be what breaks the HUD. the getTooltip function should probably just check for tooltipData being undefined and return "" in that case.

It is absolutely due to Combat Utility Belt. Disabling that module causes the Token HUD to reappear and work normally.

**Comment by Larkinabout** [comment]
Fixed in 2.1.0.
