### ISSUE TITLE
[BUG] HUD stops appearing when tokens are selected.

### ISSUE THREAD

**Issue by franckflo** [Larkinabout/fvtt-token-action-hud-core#78]
**Describe the bug**
During a game, the HUD sometimes stops appearing when a token linked to an actor is selected. I do not see any way to toggle how to it on/off to force it reapearance.

**Steps to reproduce**
Unfortunately I couldn't find a trigger for it, and there are no error message that I could find. I would be nice however to have a toggle in the left toolbar to force the HUD's appearance. Thanks!

**Versions:**
- Token Action HUD Core: 1.2.3
- Token Action HUD System: DnD 5e 1.2.2
- System: dnd5e 2.1.5
- Foundry VTT: 10.291
- Browser: tested with latest Chrome, Opera, Brave.
- 
**Additional context**
Any additional context.

**Comment by tehguitarist** [comment]
This might be linked to a similar issue where I DID get errors on PF2e lootable actors.

https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/issues/22

**Comment by Larkinabout** [comment]
Please let me know if this is still happening with Token Action HUD Core 1.3.0.

**Comment by Ironxxx** [comment]
I think this might still be happening. I don't get any HUD at all now (using PF2e) and updated to 1.3.0 for HUD and for PF2e HUD. I get the following error message in the console:

caught (in promise) TypeError: undefined. t.getContent is not a function
[Detected 1 package: token-action-hud-core]
    at CompendiumActionHandler._getPlaylistEntries (token-action-hud-core.min.js:1:15240)
    at CompendiumActionHandler.getCompendiumEntries (token-action-hud-core.min.js:1:15164)
    at CompendiumActionHandler._getCompendiumActions (token-action-hud-core.min.js:1:14764)
    at CompendiumActionHandler.buildCompendiumActions (token-action-hud-core.min.js:1:14641)
    at async ActionHandler._buildCompendiumActions (token-action-hud-core.min.js:1:20564)
    at async Promise.all (index 2)
    at async ActionHandler.buildActionList (token-action-hud-core.min.js:1:17515)
    at async TokenActionHud._updateHud (token-action-hud-core.min.js:1:65254)

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Core 1.3.1.
